### ISSUE TITLE
Diffrax runs slower than Scipy's solve_ivp

### ISSUE THREAD

**Issue by ma-sadeghi** [patrick-kidger/diffrax#82] opened 2022-03-27 21:27 UTC
Thank you so much for creating this great package!

Here's a sample script that solves the 1D heat equation discretized using the method of lines. `diffrax` turned out to be a bit slower than `scipy`'s `solve_ivp` which is not what I expected. I was expecting similar performance at worst (not even, since `diffrax` was run on GPU). Am I missing something?

```python
# %% Imports
import time
import diffrax
import jax
import jax.numpy as jnp
import numpy as np
import torch
from torchdiffeq import odeint as odeint_torch
from scipy.integrate import solve_ivp
print(f"GPU available: {torch.cuda.is_available()}")

# %% Parameters
N = 200
h = 1/(N+1)
y0 = np.ones(N, dtype="float32")
y0[0] = y0[-1] = 0.0
tspan = (0, 0.05)
saveat = np.linspace(*tspan, 10).tolist()
params = h, N

def func(t, y, dy, params, *,  use_jax=False):
    h, N = params
    if use_jax:
        idx = jnp.arange(1, N-1)
        dy = dy.at[idx].set((y[idx-1] - 2*y[idx] + y[idx+1]) / h**2)
    else:
        idx = np.arange(1, N-1)
        dy[idx] = (y[idx-1] - 2*y[idx] + y[idx+1]) / h**2
    return dy

# %% Torchdiffeq's odeint
dy = torch.zeros(N)
odefunc = lambda t, y: func(t, y, dy, params)
y0 = torch.tensor(y0)
t = torch.tensor(saveat)
start = time.time()
sol_torch = odeint_torch(odefunc, y0, t)
print(f"torchdiffeq: {time.time()-start:.2f} s")

# %% Scipy's solve_ivp
y0 = np.array(y0)
dy = np.zeros(N)
odefunc = lambda t, y: func(t, y, dy, params)
start = time.time()
sol_scipy = solve_ivp(odefunc, tspan, y0, t_eval=saveat)
print(f"solve_ivp: {time.time()-start:.2f} s")

# %% Diffrax's odeint
jax.config.update("jax_enable_x64", False)
dy = jnp.zeros(N)
odefunc = lambda t, y, args: func(t, y, dy, params, use_jax=True)
eqs = diffrax.ODETerm(odefunc)
solver = diffrax.Dopri5()
y0 = jnp.array(y0, dtype=dy.dtype)
t = diffrax.SaveAt(ts=saveat)
start = time.time()
sol_diffrax = diffrax.diffeqsolve(eqs, solver, t0=tspan[0], t1=tspan[1], dt0=5e-5, y0=y0, saveat=t)
print(f"diffrax: {time.time()-start:.2f} s")

```

```python
GPU available: True
torchdiffeq: 3.72 s
solve_ivp: 1.09 s
diffrax: 1.79 s
```

**Comment by patrick-kidger** [comment] 2022-03-28 08:04
Hey there; thanks for the clear MWE. So there's a few things that need to be changed in this example.

First of all, the tolerances are different for each library. torchdiffeq defaults to `rtol=1e-7`, `atol=1e-9`; SciPy defaults to `rtol=1e-3`, `atol=1e-5`, and Diffrax defaults to using a constant step size rather than an adaptive one. So each of your examples is doing a very different amount of computational work, to resolve the diffeq to different levels of precision.

Second, you're timing both compile time and run time. The first time you run anything that's been JIT'd, JAX will compile it. This takes a few moments. On any subsequent invocation, it will immediately hit this optimised and compiled function. When producing benchmarks, this means you should run the code once, and then time the second invocation. (In passing, run-once-time-second is a good principle when benchmarking anything.)

As a minor corollary to this. Whilst `diffrax.diffeqsolve` is already JIT-compiled, you can usually improve performance a little more by putting as much of your program inside the JIT wrapper as possible. So usually it's best to write your own function doing precisely what you want, and then JIT that.

Okay, let's bring this together. I've modified your program like so:
```python
# %% Imports
import time
import diffrax
import jax
import jax.numpy as jnp
import numpy as np
import torch
from torchdiffeq import odeint as odeint_torch
from scipy.integrate import solve_ivp
print(f"GPU available: {torch.cuda.is_available()}")

# %% Parameters
N = 200
h = 1/(N+1)
y0 = np.ones(N, dtype="float32")
y0[0] = y0[-1] = 0.0
tspan = (0, 0.05)
saveat = np.linspace(*tspan, 10).tolist()
rtol = 1e-3
atol = 1e-5

def func(t, y, dy, *,  use_jax=False):
    if use_jax:
        idx = jnp.arange(1, N-1)
        dy = dy.at[idx].set((y[idx-1] - 2*y[idx] + y[idx+1]) / h**2)
    else:
        idx = np.arange(1, N-1)
        dy[idx] = (y[idx-1] - 2*y[idx] + y[idx+1]) / h**2
    return dy

def timeit(func, y0, name):
    func(y0)
    start = time.time()
    func(y0)
    print(f"{name}: {time.time()-start:.2f} s")

# %% Torchdiffeq's odeint
dy = torch.zeros(N)
odefunc = lambda t, y: func(t, y, dy)
y0 = torch.tensor(y0)
t = torch.tensor(saveat)
solve_torch = lambda y0: odeint_torch(odefunc, y0, t, rtol=rtol, atol=atol)
timeit(solve_torch, y0, "torchdiffeq")

# %% Scipy's solve_ivp
y0 = np.array(y0)
dy = np.zeros(N)
odefunc = lambda t, y: func(t, y, dy)
solve_scipy = lambda y0: solve_ivp(odefunc, tspan, y0, t_eval=saveat, rtol=rtol, atol=atol)
timeit(solve_scipy, y0, "solve_ivp")

# %% Diffrax's odeint
jax.config.update("jax_enable_x64", False)
dy = jnp.zeros(N)
odefunc = lambda t, y, args: func(t, y, dy, use_jax=True)
eqs = diffrax.ODETerm(odefunc)
solver = diffrax.Dopri5()
stepsize_controller = diffrax.PIDController(rtol=rtol, atol=atol)
y0 = jnp.array(y0, dtype=dy.dtype)
t = diffrax.SaveAt(ts=saveat)
@jax.jit
def solve_diffrax(y0):
    return diffrax.diffeqsolve(eqs, solver, t0=tspan[0], t1=tspan[1], dt0=None, y0=y0, saveat=t,
                               stepsize_controller=stepsize_controller)
timeit(solve_diffrax, y0, "diffrax")
```

On my laptop CPU this produces the output
```
GPU available: False
torchdiffeq: 3.42 s
solve_ivp: 0.80 s
diffrax: 0.02 s
```
in which you can see that Diffrax is orders of magnitude faster than everything else.

This kind of speed improvement is completely typical when using Diffrax. torchdiffeq and solve_ivp both do most of their work in the Python interpreter, which slows things down a lot. The magic of JIT compilation means Diffrax gets optimised much further than either of those could ever hope to manage.

CC @chillee as I recall we were talking about PyTorch-vs-JAX benchmarks a while ago so this may interest you as a MWE.

**Comment by patrick-kidger** [comment] 2022-03-28 18:48
Indeed, on very small problems like this it's very common for the CPU to be faster than the GPU, so I'm not surprised that that's the case.

Incidentally, you can actually force JAX to use the CPU (even when you've installed the "GPU version" of JAX/jaxlib) in a few different ways:

Empty device list (`foo.py` can never use the GPU no matter what):
```
CUDA_VISIBLE_DEVICES= python foo.py
```

Set the preferred platform as CPU (the default backend is CPU but can explicitly GPU if you specify so in the code):
```
JAX_PLATFORM_NAME=cpu python foo.py
```

Or in the Python itself explicitly working with CPU devices (the inverse of the previous possibility -- GPU is the default but you can explicitly specify the opposite):
```
(cpu_device,) = jax.devices("cpu")
array = jax.device_put(jax.numpy.array(1), cpu_device)
```
which will actually create the array directly on the CPU (no GPU-CPU copy) due to some laziness in the way that the array is initialised.

**Comment by patrick-kidger** [comment] 2022-03-28 20:02
By the way, as the issue is resolved I'm going to close it. That's just to keep things tidy in the issue tracker; feel free to continue the discussion here / your results on scaling your problem.

**Closed by patrick-kidger** 2022-03-28 20:02 UTC
